### ISSUE TITLE
Documentation contains an insecure Resource Access Policy

### ISSUE THREAD

**Issue by Lavakumar** [DomdogSec/NodeSecurityShield#19]
The documentation contained an insecure example for the regex used to specify allowed commands.

`"allowedCommands": ["pwd" , "ls.*"]`

The regex specified above will allow arbitrary command execution as there is a wildcard after the initial **ls** command.

An attacker would use any of the shell separators to introduce and execute another command.

Please push this new update to NPM.

**Comment by thelogicalbeard** [comment]
Updated the documentation with an appropriate example and published it to NPM. ([27663a6](https://github.com/DomdogSec/NodeSecurityShield/commit/27663a6648f80c28747ac9b87f6cdc651c8d988b))
