### ISSUE TITLE
CSP Reporting can be suppressed by attacker 

### ISSUE THREAD

**Issue by Lavakumar** [DomdogSec/NodeSecurityShield#9]
Node Security Shield uses a few Node library methods to format and send the CSP report for RAP violation - https://github.com/DomdogSec/NodeSecurityShield/blob/f9e7f386168777e4a120f6a0d39067af1e560cf7/lib/attackMonitoring.js#L199

`    const data = JSON.stringify(violationEvent);`
`    const url = new URL(reportUri);`
`    const req = (url.protocol == 'https:' ? https : http).request(options, res => {`
`    req.write(data);`
`    req.end();`

If an attacker has managed to evaluate JS code in the application then these library methods (JSON.stringify, URL constructor, request constructor, req.write, req.end) can be overwritten. The overwritten variants can check if they are being invoked by Node Security Shield and behave in a manner that will prevent this issue from being reported.

Node Security Shield must take copies of all of the library methods that are used in this section and only those copies must be invoked.

**Comment by thelogicalbeard** [comment]
- Taking a copy of JSON.stringify has been addressed in #13. 

- URL Constructor is unnecessary and is removed in #13 

- However, in the case of the req constructor, even if we maintain an original copy,  an attacker can still overwrite methods used internally by http and https modules.  To avoid this from happening we might need to send 'CSP report for RAP violations' using sockets. And maintain a copy of that instead.  However, the proposed solution is complex to implement. 
I think, We can look back into this at a later point when NSS has gained popularity. For now, let's capture this in documentation under 'Known Limitations'.

**Comment by Lavakumar** [comment]
@thelogicalbeard agreed, let's document this and take this up if it become relevant in future.
